import type { ComponentType } from "react";
import { z } from "zod";
import { StandardResumeTemplate } from "~/components/resume/templates/StandardResumeTemplate";
import {
	CoreSchema,
	type ResumeTemplateConfig,
	ProjectSchema,
} from "./sharedTypes";

export const WorkExperienceSchema = z
	.object({
		title: z.string().describe("The job title."),
		company: z.string().describe("The name of the company."),
		location: z
			.string()
			.describe("The location of the job (e.g., City, Country)."),
		dates: z
			.string()
			.describe(
				"The start and end dates of the employment (e.g., Jun 2022 - Sep 2024). If current, use e.g Jun 2022 - Present. Only include months for the 2-3 most recent roles, for others use years e.g 2022 - 2024.",
			),
		accomplishments: z
			.array(
				z
					.string()
					.describe(
						"Accomplished {impact} as measured by {number} by doing {specific contribution}",
					),
			)
			.describe(`Bullet points should focus on individual accomplishments, convey self-sufficiency, that your work made a difference on your team, and that you are aware of your works impact. To do so;
            - Use numbers and quantify impact when possible. E.g. "“Led a team of 3 developers to build a dependency injection framework that was adopted by 15 teams and all 50+ developers at the company". Numbers can be several things: number of people on the team, lines of code, code coverage % before and after, SLA changes, revenue generated by the project. They can be number of users, number of installs, number of five-star ratings, number of customer support tickets you proactively resolved, and many others.
            - Use active language that shows what you have done and how you have been proactive. Use active verbs like “led”, “managed”, “drove”, “improved”, “rolled out” over passive ones like “improving” or “rolling out”.
            - Mention specific languages and technologies that you used towards the end of your description. Impact and your contribution are more important to convey than the technologies.`),
	})
	.describe(`
    Talk about impact of your work and how you contributed to it, not just what you did or were responsible for. Showcase how you have consciously and proactively added value through your actions.`);

export const TechnologyCategorySchema = z
	.object({
		category: z
			.string()
			.describe(
				"The category name (e.g., Languages, Languages & frameworks, Technologies, Other).",
			),
		item: z
			.string()
			.describe("List of technologies or skills in this category."),
	})
	.describe(
		"Short section with the most relevant technologies or skills for the role. Focus on skills that require genuine engineering knowledge and that are non-trivial. The section should feel human readable. Some of these should also be mentioned in the work experience section.",
	);

export const StandardResumeCoreDataSchema = z.object({
	workExperience: z.array(WorkExperienceSchema),
	projects: z.array(ProjectSchema).optional(),
	technologyCategories: z.array(TechnologyCategorySchema),
});

export const StandardResumeDataSchema =
	StandardResumeCoreDataSchema.merge(CoreSchema);

export const templateConfig: ResumeTemplateConfig = {
	id: "standardResume",
	defaultWorkflowId: "standardResume",
	name: "Standard Resume",
	pages: 2,
	description:
		"A professional resume layout including work experience, education, projects, and technology sections. Based on a clean, minimalist design.",
	component: StandardResumeTemplate as ComponentType<{
		data: StandardResumeData;
	}>,
	outputSchema: StandardResumeCoreDataSchema,
	componentSchema: StandardResumeDataSchema,
};

export type WorkExperience = z.infer<typeof WorkExperienceSchema>;
export type Project = z.infer<typeof ProjectSchema>;
export type TechnologyCategory = z.infer<typeof TechnologyCategorySchema>;
export type StandardResumeCoreData = z.infer<
	typeof StandardResumeCoreDataSchema
>;
export type StandardResumeData = z.infer<typeof StandardResumeDataSchema>;
